# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eLCCtbwJugdlwLLQGx2nb9mk5uYZe8BF
"""

import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv('/content/mtcars.csv')
plt.scatter(df['mpg'],df['wt'],color="blue")
plt.title('Scatter Plot')
plt. xlabel('mpg')
plt.ylabel('wt')
plt.grid(True)
plt.show()